# fly.toml app configuration file generated for drizzle-flyway on 2025-08-09T06:25:09+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'drizzle-flyway'
primary_region = 'sin'

[env]
  PORT = "8080"
  STORE_PATH = "/app"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  http_options.response.pristine = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "drizzle_flyway"
  initial_size = "1gb"
  auto_extend_size_increment = "1gb"
  auto_extend_size_limit = "5gb"
  auto_extend_size_threshold = 75
  destination = "/app"
