# fly.toml app configuration file generated for drizzle-flyway on 2025-08-09T10:48:23+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'drizzle-flyway'
primary_region = 'sin'

[build]
  image = 'ghcr.io/drizzle-team/gateway:latest'

[env]
  PORT = '8080'
  STORE_PATH = '/app'

[[mounts]]
  source = 'drizzle_flyway'
  destination = '/app'
  initial_size = '1gb'
  auto_extend_size_threshold = 75
  auto_extend_size_increment = '1gb'
  auto_extend_size_limit = '5gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.http_options]
    [http_service.http_options.response]
      pristine = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
